/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connector.HibernateUtil;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import model.*;
import org.hibernate.Query;
import org.hibernate.Transaction;

/**
 *
 * @author Casa
 */
public class jifCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form Curso
     */
    private Usuario user;
    public jifCurso() {
        initComponents();
        getAll();
        getAllDepartamentos();
    }
    
    public jifCurso(Usuario user) {
        initComponents();
        this.user = user;
        CheckUser();
        getAll();
        getAllDepartamentos();
    }
    
    public void CheckUser(){
        String tipo = this.user.getTipo();
        if(tipo.compareTo("comum") == 0){
            jBtCadastrar.setEnabled(false);
            jBtDeletar.setEnabled(false);
        }
        
    }
    
    public void getAll(){
        String sql = "from Curso c";   
        
        SessionFactory sf = HibernateUtil.getSessionFactory(); 
        Session session = sf.openSession();
        Query query = session.createQuery(sql);
        List<Curso> results = (List<Curso>)query.list();
        
        for(Curso c : results){
            jCbCursos.addItem(c);
        }        
        
        session.close();
    }
    
    public void getAllDepartamentos(){
        String sql = "from Departamento c";   
        
        SessionFactory sf = HibernateUtil.getSessionFactory(); 
        Session session = sf.openSession();
        Query query = session.createQuery(sql);
        List<Departamento> results = (List<Departamento>)query.list();
        
        for(Departamento d : results){
            jCbDepartamentos.addItem(d);
        }        
        
        session.close();
    }
    
    public boolean checkFields(){
        boolean resp = false;
        
        if(jTfNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o nome!");
        }
        else if(jCbDepartamentos.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Selecione o departamento!");
        }
        else{
            resp = true;
        }
        
        return resp;
    }
    
    public String createSQLSelect(){
        String sql = "Select c from Curso c ";
        Departamento d = (Departamento) jCbDepartamentos.getSelectedItem();
        String where = " where ";
        boolean joinFlag = false;
        boolean whereFlag = false;
        String join = " inner join ";
        if(d != null){
            join = join+" c.departamento as d";
            where = where+" d.codigo = "+d.getCodigo();
            whereFlag = true;
            joinFlag = true;
        }
        if(!jTfNome.getText().isEmpty()){
            if(whereFlag){
                where = where + " AND ";
            }
            where = where+" c.Nome = '"+jTfNome.getText()+"'";
            whereFlag = true;
        }
        
        
        if(joinFlag){
            sql = sql+join;
        }
        if(whereFlag){
            sql = sql+where;
        }
        return sql;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCursos = new javax.swing.JList<>();
        jLbNome = new javax.swing.JLabel();
        jTfNome = new javax.swing.JTextField();
        jCbDepartamentos = new javax.swing.JComboBox<>();
        jLbDepartamento = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jBtCadastrar = new javax.swing.JButton();
        jBtConsultar = new javax.swing.JButton();
        jCbCursos = new javax.swing.JComboBox<>();
        jBtSelecionar = new javax.swing.JButton();
        jBtDeletar = new javax.swing.JButton();
        jLbCursos = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Curso");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jScrollPane1.setViewportView(jListCursos);

        jLbNome.setText(" Nome :");

        jLbDepartamento.setText("Departamento :");

        jBtCadastrar.setText("Cadastrar");
        jBtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCadastrarActionPerformed(evt);
            }
        });

        jBtConsultar.setText("Consultar");
        jBtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtConsultarActionPerformed(evt);
            }
        });

        jBtSelecionar.setText("Selecionar");
        jBtSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSelecionarActionPerformed(evt);
            }
        });

        jBtDeletar.setText("Deletar");
        jBtDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDeletarActionPerformed(evt);
            }
        });

        jLbCursos.setText("Cursos :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbNome)
                                    .addComponent(jCbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLbDepartamento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtConsultar)
                                    .addComponent(jBtCadastrar))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbCursos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLbNome)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jBtCadastrar)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLbDepartamento)
                                        .addGap(11, 11, 11)
                                        .addComponent(jCbDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jBtConsultar)))
                                .addGap(36, 36, 36)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbCursos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtSelecionar))
                                .addGap(18, 18, 18)
                                .addComponent(jBtDeletar)))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCadastrarActionPerformed
        if(checkFields()){
            SessionFactory af =  HibernateUtil.getSessionFactory();
            Session session = af.openSession();
            
            Curso c = new Curso();
            c.setNome(jTfNome.getText());
            
            Departamento d = (Departamento) jCbDepartamentos.getSelectedItem();
            
            c.setCodigo(d.getCodigo());
            
            Transaction tx = session.beginTransaction();
            
            session.saveOrUpdate(c);
            
            tx.commit();
        
            session.flush();

            session.close();
        }
    }//GEN-LAST:event_jBtCadastrarActionPerformed

    private void jBtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtConsultarActionPerformed
        DefaultListModel lista = new DefaultListModel();
        String sql = createSQLSelect();
        if(sql.isEmpty()){
            sql = "from Curso c";
        }                    
        SessionFactory sf = HibernateUtil.getSessionFactory(); 
        Session session = sf.openSession();
        Query query = session.createQuery(sql);
        
        List<Curso> results = (List<Curso>)query.list();
        for(Curso c : results){
            lista.addElement(c.getNome());
        }
        
        jListCursos.setModel(lista);
        
        session.close();
    }//GEN-LAST:event_jBtConsultarActionPerformed

    private void jBtSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSelecionarActionPerformed
        
        Curso c = (Curso) jCbCursos.getSelectedItem();
        
        jTfNome.setText(c.getNome());
        
        // selecionar o comboBox
        
    }//GEN-LAST:event_jBtSelecionarActionPerformed

    private void jBtDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDeletarActionPerformed
        
        Curso c = (Curso) jCbCursos.getSelectedItem();
        if(c != null){
            SessionFactory af =  HibernateUtil.getSessionFactory();
            Session session = af.openSession();
                       
            
            String hql = "DELETE FROM Curso "  + 
             "WHERE codigo = :codigo";
            
                        
            Query query = session.createQuery(hql);
            query.setInteger("codigo", c.getCodigo());
            
            Transaction tx = session.beginTransaction();
        
            int result = query.executeUpdate();
            
            tx.commit();
            
            if(result>0){
                JOptionPane.showMessageDialog(null, "Curso removido");
            }else{
                JOptionPane.showMessageDialog(null, "Houve um problema na remoção");
            }
            
            session.flush();

            session.close();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Curso");
        }   
        
    }//GEN-LAST:event_jBtDeletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCadastrar;
    private javax.swing.JButton jBtConsultar;
    private javax.swing.JButton jBtDeletar;
    private javax.swing.JButton jBtSelecionar;
    private javax.swing.JComboBox<Object> jCbCursos;
    private javax.swing.JComboBox<Object> jCbDepartamentos;
    private javax.swing.JLabel jLbCursos;
    private javax.swing.JLabel jLbDepartamento;
    private javax.swing.JLabel jLbNome;
    private javax.swing.JList<Object> jListCursos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTfNome;
    // End of variables declaration//GEN-END:variables
}
