/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connector.HibernateUtil;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Curso;
import model.Historico;
import model.Usuario;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.exception.GenericJDBCException;

/**
 *
 * @author Casa
 */
public class jifHistorico extends javax.swing.JInternalFrame {

    /**
     * Creates new form Historico
     */
    private Usuario user;
    private Aluno aluno;
    public jifHistorico() {
        initComponents();
    }
    
    public jifHistorico(Usuario user) {
        initComponents();
        this.user = user;
    }
    
    public boolean check(){
        boolean resp = false;
        
        if(jTfMatricula.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite a matricula!");
        }
        else if(jTfCurso.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite o !");
        }
        else if(jTfNota.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite a nota!");
        }
        else{
            resp = true;
        }
        
        return resp;
    }
    
    public boolean buscarAluno() {
        boolean resp = false;
        DefaultListModel lista = new DefaultListModel();
        String sql;
        sql = "Select a.* from Aluno a "
                + " inner join Matricula m On m.cpf_aluno = a.cpf "
                + " where m.matricula_aluno = :matricula";
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        
        Query query = session.createSQLQuery(sql);
        query.setString("matricula", jTfMatricula.getText());
        List<Aluno> results = (List<Aluno>) query.list();
        if (results.size() > 0) {
            this.aluno = results.get(0);
            resp = true;
        } else {
            JOptionPane.showMessageDialog(null, "Aluno não encontrado!");
        }

        session.close();

        return resp;
    }
    
    public boolean buscarCurso(){
        boolean resp = false;
        
        String sql;
        sql = "Select c.* from Curso c where c.nome = :nome ";
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        
        Query query = session.createSQLQuery(sql);
        query.setString("nome", jTfCurso.getText());
        List<Curso> results = (List<Curso>) query.list();
        if (results.size() > 0) {
            resp = true;
        } else {
            JOptionPane.showMessageDialog(null, "Curso não encontrado!");
        }

        session.close();
        
        return resp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTfMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfNota = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListHistorico = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jTfCurso = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Historico");

        jLabel1.setText("Matricula : ");

        jLabel2.setText("Nota final :");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("Gerar Historico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("consultar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListHistorico);

        jLabel3.setText("Nome Curso :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTfNota, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(7, 7, 7)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (check() && buscarAluno() && buscarCurso()) {
            SessionFactory af = HibernateUtil.getSessionFactory();
            Session session = af.openSession();
            Transaction tx = session.beginTransaction();
            try{
                    String sql = "call InsereHistorico('"+jTfCurso.getText()+"','"+jTfMatricula.getText()+"',"+Float.parseFloat(jTfNota.getText())+",'2018/12/04')";
                    Query query = session.createSQLQuery("call InsereHistorico(:curso,:matricula,:nota,:data)");
                    query.setString("matricula", jTfMatricula.getText());
                    query.setString("curso", jTfCurso.getText());
                    query.setFloat("nota", Float.parseFloat(jTfNota.getText()));
                    query.setString("data", "2018/12/04");
                    int result = query.executeUpdate();
                    
                    JOptionPane.showMessageDialog(null, "Historico registrado.");
                
                    tx.commit();
            }
            catch(GenericJDBCException e){                 
                JOptionPane.showMessageDialog(null,e.getCause().getMessage());
//                af.getCurrentSession().getTransaction().rollback();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
//                af.getCurrentSession().getTransaction().rollback();
            }
            finally{
                session.flush();
                session.close();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        DefaultListModel lista = new DefaultListModel();
//        String sql = createSQLSelect();
        String sql =  "from Historico h ";
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.openSession();
        Query query = session.createQuery(sql);
        List<Historico> results = (List<Historico>) query.list();
        for (Historico a : results) {
            lista.addElement( a.getData_cursada() + " | " + a.getNota_final());
        }

        jListHistorico.setModel(lista);

        session.close();
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListHistorico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTfCurso;
    private javax.swing.JTextField jTfMatricula;
    private javax.swing.JTextField jTfNota;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
