
package View;

import Connector.HibernateUtil;
import java.util.List;
import model.*;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
public class Main extends javax.swing.JFrame {

    private Usuario user;
    
    public Main() {
        initComponents();
    }
    
    public Main(Usuario user){
        this.user = user;
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDPMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMProfessor = new javax.swing.JMenuItem();
        jMCurso = new javax.swing.JMenuItem();
        jMDepartamento = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDPMain.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDPMainLayout = new javax.swing.GroupLayout(jDPMain);
        jDPMain.setLayout(jDPMainLayout);
        jDPMainLayout.setHorizontalGroup(
            jDPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        jDPMainLayout.setVerticalGroup(
            jDPMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jMenu1.setText("Tabelas");

        jMenuItem1.setText("Aluno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMProfessor.setText("Professor");
        jMProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMProfessorActionPerformed(evt);
            }
        });
        jMenu1.add(jMProfessor);

        jMCurso.setText("Curso");
        jMCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCursoActionPerformed(evt);
            }
        });
        jMenu1.add(jMCurso);

        jMDepartamento.setText("Departamento");
        jMDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDepartamentoActionPerformed(evt);
            }
        });
        jMenu1.add(jMDepartamento);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Serviços");

        jMenu4.setText("Aluno");

        jMenuItem2.setText("Adicionar aluno na turma");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenu3.add(jMenu4);

        jMenu2.setText("Turma");

        jMenuItem3.setText("Formar turma");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenu3.add(jMenu2);

        jMenu5.setText("Departamento");
        jMenu3.add(jMenu5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDPMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        final jifAluno telaAluno = new jifAluno(this.user);
        jDPMain.add(telaAluno);
        telaAluno.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMProfessorActionPerformed
        final jifProfessor TelaProfessor = new jifProfessor(this.user);
        jDPMain.add(TelaProfessor);
        TelaProfessor.show();
    }//GEN-LAST:event_jMProfessorActionPerformed

    private void jMCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCursoActionPerformed
        final jifCurso telaCurso = new jifCurso(this.user);
        jDPMain.add(telaCurso);
        telaCurso.show();
    }//GEN-LAST:event_jMCursoActionPerformed

    private void jMDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDepartamentoActionPerformed
        final jifDepartamento telaDepartamento = new jifDepartamento(this.user);
        jDPMain.add(telaDepartamento);
        telaDepartamento.show();
    }//GEN-LAST:event_jMDepartamentoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        final jifCadastroAD telaCadastroTurma = new jifCadastroAD(this.user);
        jDPMain.add(telaCadastroTurma);
        telaCadastroTurma.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        final jifFormarTurma telaFormarTurma = new jifFormarTurma(this.user);
        jDPMain.add(telaFormarTurma);
        telaFormarTurma.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDPMain;
    private javax.swing.JMenuItem jMCurso;
    private javax.swing.JMenuItem jMDepartamento;
    private javax.swing.JMenuItem jMProfessor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
